---
title: "About Me"
format:
  html:
    page-layout: full
---

Hi! I'm Will Decker and I am an undergraduate honors student at Louisiana State University in Baton Rouge, LA, USA.

Most notably, my interests and passions fall within the field of cognitive neuroscience. I am generally curious about 1) learning, 2) language, 3) semantic knowledge and 4) neuroimaging. I am interested in how we learn and make sense of the complex visual, linguistic and auditory world around us. How do we learn language? How do we learn about, and perceive events during conversations? How can we understand the cognitive and computational mechanisms of learning and language using neuroimaging and complex models? These are just some of the many questions I am interested in pursuing. 

I am also severely interested in neuroimaging techniques (MRI, EEG, MEG, etc.), their respective analyses and improvements to analyses (qualitatively and quantitatively). I am intrigued by how the brain can be broken down computationally and how this understanding influences our characterization of cognitive processes. Additionally, I am generally interested in and passionate about the structure-function relationship, open science, coding and statistics.

Currently, I am focused on statistical learning (SL), the computations involved (i.e., transitional probabilities and chunking), the neural mechanisms supporting SL in the adult and developing brain, and the computational techniques, like Hidden Markov Models (HMMs) or multi-voxel pattern analysis (MVPA) to better understand SL and the brain's ability to derive meaning from the environment.

On top of being a student, I am a Project Coordinator in the [Language, Environment and NeuroDevelopment (LEND) Lab](https://juschnei.wixsite.com/lendlab) under the mentorship of [Julie M. Schneider, PhD](https://www.lsu.edu/hss/comd/faculty/schneider.php) where I have learned lots about EEG and the signal processing operations behind it and lead a team of other undergraduates in learning and conducting EEG experiments. I am also an honors thesis student in the [Representations and Learning (ReLearn) Lab](https://faculty.lsu.edu/chriscox/index.php) under the mentorship of [Christopher Cox, PhD](https://www.lsu.edu/hss/psychology/faculty/cognitive/cox.php) where I have delved deep into MRI, SL and much more.

Additionally, I am a big foodie and will eat practically anything. (Except raisins. Who wants a dried, shriveled grape when you can have a nice, juicy, good tasting one? They smell weird too.) I do enjoy my fair share of television; my favorite show--without a doubt--is The Simpsons. I also enjoy walking around outside when the weather is nice and listening to my favorite song, "The Night Chicago Died" by Paper Lace. I have also been playing the violin for 10+ years.

At the moment, I am working towards entering a collaborative and open-science driven graduate program in Cognitive Psychology and/or Cognitive Neuroscience with opportunities to enhance my knowledge of language, neuroimaging, statistics and data science as well as receive detailed training in being a scientist of the brain.

---