---
title: "Archive"
format:
  html:
    page-layout: full
    theme: dark
---

Here you will find past projects that have been completed. There are other projects which have since been completed; however, the following descriptions are from projects that I felt significantly added to the characterization of my science and research interests.

## A Look at Rhyme's Role in Word Learning in Adults

Phonological and semantic cues have been shown to significantly bolster word learning by aiding in encoding. Previous behavioral examinations into this exact phenomena through rhyme have demonstrated such an outcome, yet, the speed and depth  of rhyme's aid in word learning is not quite understood. To uncover the true nature of rhyme's role in word learning, we  used EEG and ERP methods to characterize this phenomena. We specifically examined the N400 ERP component and found a significant attenuation across exposure to our paradigm and deduced that rhyme may serve as a more implicit faclitator of encoding. The resultant poster from this project can be found [here](https://github.com/w-decker/Presentations/blob/main/CNS-2023.pdf).


## Quality of Neural Data Between Two EEG Capping Approaches

Given EEG's relatively low cost, there eixists a variety of capping approaches scientists may use to conduct research. However, there are fundamental differences between brands, electrodes, amplifiers that effect data and data collection. In this project, I evaluated the qulitative and quantitive differences between BrainVision's EasyCap and R-Net--two caps that differ in there implementation and data collection. For example, the R-Net uses passive electrodes whereas the EasyCap uses active electrodes. (The distinction between "active" and "passive" electrodes is the place of amplification of the signal). We found significant differences in the data processing operations used during preprocessing and identified qualititative differences across caps as well. This resultant poster from this project can be found [here](https://github.com/w-decker/Presentations/blob/main/LSU_Discover_Day_2022.pdf).

---

## Project Tracker

| Date of Update | Project |
| ---- | ------- | 
| 07/02/2023 | A Look at Rhyme's Role in Word Learning in Adults |
| 07/02/2023 | Quality of Neural Data Between Two EEG Capping Approaches |