---
title: "Current Projects"
format:
  html:
    page-layout: full
    theme: dark
---

Below are brief synopses of current projects that I am working on. Naturally, there are other projects at various stages; however, the following descriptions are from projects which I felt significantly added to the characterization of my science and research interests.

---

## Slice-timing Correction or Temporal Derivatives?

Because slices of fMRI volumes are not collected simultaneously, the BOLD response exhibits a temporal lag across slices. This can be partially ameliorated by following multibanding procedures (factor of 3 is usually good) but this does not fix everything. One possible option is to use a slice-timing corrective measure during the preprocessing stage of the fMRI analysis. Another option is to use a temporal derivative as an additional "nuisance" variable in the GLM. But which of the latter two options is better? To test this, we can use a non-nested model comparison at the voxel-wise level by measuring the difference of varience at each voxel across the two models. 

_Keywords_: fMRI, slice-timing, temporal derivative

## Real-time Manipulations of Learning 

Can learning be inhibited or promoted by tracking neural activity? Using neural entrainment, we plan to ask this very question about statistical learning. What are the subsequent consequences of such manipulations? How does this affect behavioral outcomes? Encoding? Neural profiles?

_Keywords_: Neural entrainment, statistical learning, neurofeedback

## The Architecture of Auditory Statistical Learning

Statistical learning (SL) is the neuro-cognitive mechanism that the brain employs to identify, parse and extract meaning from continuous input by identifying statistical patterns such as transitional probabilites (TPs). SL can be observed across a variety of cognitive domains and is particularly relevant in the language domain. It has been shown that langauge acquisition occurs through SL. However, previous neuroimaging studies characterize the learning of meaning via auditory SL as static when, rather, learning occurs across the temporal domain, employing various neural regions across space. The focus of this current project is to idetify the spatiotemporal architecure of SL. The timescales at which the brain identifies and processes statistics and along what neural space this occurs is of great interest. 

This project is partially funded by the Tiger Athletic Foundation (TAF) Scholarship Supporting Undergraduate Honors Thesis Research!

_Keywords:_ fMRI, statistical learning, langauge, dynamic functional connectivity

---

## Optimized Pipeline for Developmental ERPs

This project is partially funded by an LSU Discover Project Grant. This project involves examining data quality metrics for developmental EEG/ERP data and identifying optimized preprocessing operations from such data with the ultimate end goal of producing an open-access, easily executable pipeline for researchers. If you are interested in the in-progress pipeline, check out the GitHub repo [here](https://github.com/w-decker/DevERP-Simplified) where a detailed wiki has been constructed of everything completed thus far. If you are interested in the analysis being used, check out that GitHub repo [here](https://github.com/w-decker/DevERP-Analysis). 

In recent years, a call for standardization of EEG preprocessing methods has been amplified and studies aimed at identifying the best preprocessing criterion determined that there exists some limited range of parameters one can process EEG data through before compromising data quality, statistical significance and reproducibility. However, this research primarily consisted of adult EEG data. Given the exogenous and endogenous impacts of developmental populations on EEG data, a distinct evaluation of the best preprocessing methods for developmental data must be made. This is—in short—the foundation of the project.

_Keywords:_ EEG, ERP, quality metrics, developmental

---

## Project Tracker

| Date of Update | Project | New or Moved to Archive? |
| ---- | ------- | ---------------------------------- |
| 11/26/2023 | Slice-timing Correction or Temporal Derivatives? | New |
| 11/26/2023 | Real-time Manipulations of Learning | New |
| 07/02/2023 | The Architecture of Auditory Statistical Learning | New |
| 07/02/2023 | Optimized Pipeline for Developmental ERPs | New |