---
title: "Open Science"
format: html
---

Open science is integral to creating good science. Adherence to such practices supports the transparent dissemination of information which concurrently increases the trust in the scientific community and allows research to be replicated and validated. Thusly, I have included some resources that I've found seminal in my personal development and understanding of what it means to conduct open science as well as the sites that I use to share the research that I am a part of and conduct.

Open science is a multi-tiered practice that consists of multiple concepts like reproducibility, accessibility, transparency, diversity and analytical rigor. It cannot simply be described in one paragraph and to understand it requires much more than the resources I've provided. I am still learning and will be continuing to learn about open science.

---

## Resources

The resources listed below are some of the many that have influenced my drive for open science and aided in my ability to conduct open science. If you have other sources of knowledge regarding open science and its implementation, please reach out!

1. [Psychology needs to get tired of winning. (Haeffel 2022).](https://royalsocietypublishing.org/doi/10.1098/rsos.220099)

2. [EEG is better left alone (Delorme 2023)](https://www.nature.com/articles/s41598-023-27528-0)

3. [Science has a nasty photoshopping problem (Bik 2022)](https://www.nytimes.com/interactive/2022/10/29/opinion/science-fraud-image-manipulation-photoshop.html?smid=url-share)

4. [Brain Imaging Data Structure (BIDS)](https://bids.neuroimaging.io/)

5. [Center for Open Science](https://www.cos.io/)

---